### ISSUE TITLE
ServiceUnitTest does not recognise Data Services as Services

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-testing-support#11]
For the next domain name: 

```
package demo

class Book {

    String name

    static constraints = {
    }
}
```

and service: 

```
package demo

import grails.gorm.services.Service
import groovy.transform.CompileStatic

@CompileStatic
@Service(Book)
abstract class BookService {
    abstract List<Book> findAll()
}
```

The next test: 

package demo

```
import grails.testing.gorm.DataTest
import grails.testing.services.ServiceUnitTest
import spock.lang.Specification

class BookServiceSpec extends Specification implements ServiceUnitTest<BookService>, DataTest {

    def setup() {
        mockDomain(Book)
    }

    void "test there are not book"() {
        expect:
        service.findAll().size() == 0
    }
}

```

throws the error ` Cannot add Service class [class demo.BookService]. It is not a Service!`

```
    org.spockframework.runtime.ConditionFailedWithExceptionError at BookServiceSpec.groovy:19
        Caused by: org.grails.core.exceptions.GrailsConfigurationException at BookServiceSpec.groovy:19

Condition failed with Exception:

service.findAll().size() == 0
|
org.grails.core.exceptions.GrailsConfigurationException: Cannot add Service class [class demo.BookService]. It is not a Service!

Condition failed with Exception:

service.findAll().size() == 0
|
org.grails.core.exceptions.GrailsConfigurationException: Cannot add Service class [class demo.BookService]. It is not a Service!

	at demo.BookServiceSpec.test there are not book(BookServiceSpec.groovy:19)
Caused by: org.grails.core.exceptions.GrailsConfigurationException: Cannot add Service class [class demo.BookService]. It is not a Service!
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:855)
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:517)
	at grails.testing.services.ServiceUnitTest$Trait$Helper.mockArtefact(ServiceUnitTest.groovy:37)
	at org.grails.testing.ParameterizedGrailsUnitTest$Trait$Helper.getArtefactInstance(ParameterizedGrailsUnitTest.groovy:48)
	at grails.testing.services.ServiceUnitTest$Trait$Helper.getService(ServiceUnitTest.groovy:51)
	... 1 more
```

**Comment by jameskleeh** [comment]
Fixed in 1.0.1-SNAPSHOT
