### ISSUE TITLE
Execute samples in test project - ApplicationEventMulticaster not initialized error

### ISSUE THREAD

**Issue by niravassar** [grails/grails-testing-support#2]
The outstanding issue is that when i create an app with create-app, and then do the examples in the doc, all the tests pass but i am getting a exception. Looks like a spring boot lifecyle exception. Note it does not occur in the demo code. 

```java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.web.context.support.GenericWebApplicationContext@6e9319f: startup date [Mon May 01 11:52:04 CDT 2017]; root of context hierarchy at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) at org.s```

**Comment by niravassar** [comment]
**ControllerUnitTest**

- the imported 1.0.0.BUILD-SNAPSHOT does not pull in packages grails.testing.web, grails.testing.web.controllers, grails.testing.web.taglib, grails.testing.gorm

**TabLib tests*

- same; no package pulled in

**HelperServiceSpec**
- test passes but i get ERROR below. If I use @TestFor(HelperService) then it doesnt give the error and it passes
`java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.web.context.support.GenericWebApplicationContext@6e9319f: startup date [Mon May 01 11:52:04 CDT 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
	at org.s`

**ReportingServiceSpec**
- test passes with DI but still has the ApplicationEventMulticaster not initialized exception

**Comment by niravassar** [comment]
**RunOnceSpec**
- wondering what this counter is for specifically, it has the same effect as onceBeforeCounter - is it redundant?
`int anotherOnceBeforeCounter = 0`

- OnceBeforeSpec ran flawlessly
- DependencyInjectionSpec ran flawlessly

**Comment by niravassar** [comment]
i believe this is due to the fact that i did not run this with grails 3.3
