### ISSUE TITLE
inconsistent query results after updating domain instances in a service (DataTest/ServiceUnitTest)

### ISSUE THREAD

**Issue by zyro23** [grails/grails-testing-support#35]
given a unit test (`DataTest`, `ServiceUnitTest`), after updating domain objects (i.e. persistent entity instances) in a `@Transactional` service, subsequent queries produce inconsistent/wrong results with instances still having the old/pre-update values.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app tests (`DummySpec`)
2. see test failures

### Expected Behaviour

* sample app tests should pass

### Actual Behaviour

```
Condition failed with Exception:

dummyWithNewNameFromService.name == "updatedDummyExplicit"
|                           |
null                        java.lang.NullPointerException: Cannot get property 'name' on null object


	at myapp.DummySpec.test find after update with explicit flush from service_closure1(DummySpec.groovy:30)
	at myapp.DummySpec.test find after update with explicit flush from service_closure1(DummySpec.groovy)
	at groovy.lang.Closure.call(Closure.java:418)
	at spock.lang.Specification.verifyAll(Specification.java:223)
	at myapp.DummySpec.test find after update with explicit flush from service(DummySpec.groovy:25)
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
	... 5 more


Condition not satisfied:

!dummyWithOldName
||
|myapp.Dummy : 1
false


	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy:47)
	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy)
	at groovy.lang.Closure.call(Closure.java:418)
	at spock.lang.Specification.verifyAll(Specification.java:223)
	at myapp.DummySpec.test find after update with implicit flush from service(DummySpec.groovy:45)


Condition failed with Exception:

dummyWithNewName.name == "updatedDummyImplicit"
|                |
null             java.lang.NullPointerException: Cannot get property 'name' on null object


	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy:48)
	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy)
	at groovy.lang.Closure.call(Closure.java:418)
	at spock.lang.Specification.verifyAll(Specification.java:223)
	at myapp.DummySpec.test find after update with implicit flush from service(DummySpec.groovy:45)
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
	... 5 more


Condition failed with Exception:

dummyWithNewNameFromService.name == "updatedDummyImplicit"
|                           |
null                        java.lang.NullPointerException: Cannot get property 'name' on null object


	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy:50)
	at myapp.DummySpec.test find after update with implicit flush from service_closure2(DummySpec.groovy)
	at groovy.lang.Closure.call(Closure.java:418)
	at spock.lang.Specification.verifyAll(Specification.java:223)
	at myapp.DummySpec.test find after update with implicit flush from service(DummySpec.groovy:45)
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
	... 5 more
```

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.5
- **JDK Version:** oracle 8u151
- **Container Version (If Applicable):** n/a

### Example Application

a simplified sample app will be referenced in a minute, see `DummySpec` (and the different failues for each of the two test methods).

if there is anything i can do to help/speed-up fixing this, just gimme a ping.

**Comment by jameskleeh** [comment]
I don't think there is any bug here, other than your service. You were hard coding the name in the update method and were missing a `save` call in another method.

```
@@ -14,11 +14,10 @@ class DummyService {
        void updateWithImplicitFlush(String oldName, String newName) {
                Dummy dummy = Dummy.findByName oldName
                dummy.name = newName
-               dummy.save()
        }
 
        Dummy findByName(String name) {
-               return Dummy.findByName(name)
+               return Dummy.findByName("updatedDummy")
        }
 
 }
```

That patch allows the test to pass

**Comment by zyro23** [comment]
oops! hard-coded name was not intentional. i removed the hard-coded "updatedDummy" and used `name`.

reg. the `save` method call: do you really think that should be required? because updating a persistent instance in a transaction (with flush mode `COMMIT` or `AUTO` at least) should save/flush/persist that dirty instance on commit shouldnt it?

im happy to be corrected there, even more so if this is not-a-bug :)

**Comment by jameskleeh** [comment]
@zyro23 That may be the case for Hibernate, but not for the in memory datastore

**Comment by zyro23** [comment]
oh was not aware of that! thank you!
